# SPDX-FileCopyrightText: 2026-present SPDX Contributors
# SPDX-License-Identifier: Apache-2.0

name: Build wheels

on:
  push:
    branches: [ master ]
    paths:
      - "spdx_license_matcher/**"
      - "src/**"
      - "pyproject.toml"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "spdx_license_matcher/**"
      - "src/**"
      - "pyproject.toml"
      - ".github/workflows/build.yml"

jobs:
  build-wheel:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.9", "3.10", "3.14" ]
      fail-fast: true

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          pip install --upgrade build pip
          pip install .

      - name: Build wheel
        id: build
        run: |
          python -m build
